name: Tests and docs

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 17 ]
        db: [ h2, hsqldb, mysql, postgres ]
        provider: [ hibernate, eclipselink ]


    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_DATABASE: jpa_test
            MYSQL_ROOT_PASSWORD: root
        ports:
          # Maps port on service container to the host
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres
        env:
          POSTGRES_DB: jpa_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port on service container to the host
          - 5432:5432
    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
        cache: 'maven'
    - name: Run all tests
      run: mvn clean verify -P ${{ matrix.db }},${{ matrix.provider }}

  deploy_develop_docs:
    name: Deploy development docs
    needs: tests
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_site.yml@v1
    with:
      branch: develop
      host: docs.bernardomg.com
    secrets:
      url: ${{ secrets.DEPLOY_DOCS_DEVELOP_SITE }}
      username: ${{ secrets.DEPLOY_DOCS_DEVELOP_USER }}
      password: ${{ secrets.DEPLOY_DOCS_DEVELOP_PASSWORD }}

  deploy_docs:
    name: Deploy docs
    needs: tests
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_site.yml@v1
    with:
      branch: master
      host: docs.bernardomg.com
    secrets:
      url: ${{ secrets.DEPLOY_DOCS_SITE }}
      username: ${{ secrets.DEPLOY_DOCS_USER }}
      password: ${{ secrets.DEPLOY_DOCS_PASSWORD }}